 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author ANH DUC
 */
public class CalculatorView extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorView
     */
    public CalculatorView() {
        initComponents();
    }

    public JButton getBtnAdd() {
        return btnAdd;
    }

    public void setBtnAdd(JButton btnAdd) {
        this.btnAdd = btnAdd;
    }

    public JButton getBtnDiv() {
        return btnDiv;
    }

    public void setBtnDiv(JButton btnDiv) {
        this.btnDiv = btnDiv;
    }

    public JButton getBtnDot() {
        return btnDot;
    }

    public void setBtnDot(JButton btnDot) {
        this.btnDot = btnDot;
    }

    public JButton getBtnFlip() {
        return btnFlip;
    }

    public void setBtnFlip(JButton btnFlip) {
        this.btnFlip = btnFlip;
    }

    public JButton getBtnMAdd() {
        return btnMAdd;
    }

    public void setBtnMAdd(JButton btnMAdd) {
        this.btnMAdd = btnMAdd;
    }

    public JButton getBtnMC() {
        return btnMC;
    }

    public void setBtnMC(JButton btnMC) {
        this.btnMC = btnMC;
    }

    public JButton getBtnMR() {
        return btnMR;
    }

    public void setBtnMR(JButton btnMR) {
        this.btnMR = btnMR;
    }

    public JButton getBtnMSub() {
        return btnMSub;
    }

    public void setBtnMSub(JButton btnMSub) {
        this.btnMSub = btnMSub;
    }

    public JButton getBtnMulti() {
        return btnMulti;
    }

    public void setBtnMulti(JButton btnMulti) {
        this.btnMulti = btnMulti;
    }

    public JButton getBtnNum0() {
        return btnNum0;
    }

    public void setBtnNum0(JButton btnNum0) {
        this.btnNum0 = btnNum0;
    }

    public JButton getBtnNum1() {
        return btnNum1;
    }

    public void setBtnNum1(JButton btnNum1) {
        this.btnNum1 = btnNum1;
    }

    public JButton getBtnNum2() {
        return btnNum2;
    }

    public void setBtnNum2(JButton btnNum2) {
        this.btnNum2 = btnNum2;
    }

    public JButton getBtnNum3() {
        return btnNum3;
    }

    public void setBtnNum3(JButton btnNum3) {
        this.btnNum3 = btnNum3;
    }

    public JButton getBtnNum4() {
        return btnNum4;
    }

    public void setBtnNum4(JButton btnNum4) {
        this.btnNum4 = btnNum4;
    }

    public JButton getBtnNum5() {
        return btnNum5;
    }

    public void setBtnNum5(JButton btnNum5) {
        this.btnNum5 = btnNum5;
    }

    public JButton getBtnNum6() {
        return btnNum6;
    }

    public void setBtnNum6(JButton btnNum6) {
        this.btnNum6 = btnNum6;
    }

    public JButton getBtnNum7() {
        return btnNum7;
    }

    public void setBtnNum7(JButton btnNum7) {
        this.btnNum7 = btnNum7;
    }

    public JButton getBtnNum8() {
        return btnNum8;
    }

    public void setBtnNum8(JButton btnNum8) {
        this.btnNum8 = btnNum8;
    }

    public JButton getBtnNum9() {
        return btnNum9;
    }

    public void setBtnNum9(JButton btnNum9) {
        this.btnNum9 = btnNum9;
    }

    public JButton getBtnPercent() {
        return btnPercent;
    }

    public void setBtnPercent(JButton btnPercent) {
        this.btnPercent = btnPercent;
    }

    public JButton getBtnPerform() {
        return btnPerform;
    }

    public void setBtnPerform(JButton btnPerform) {
        this.btnPerform = btnPerform;
    }

    public JButton getBtnSquareRoot() {
        return btnSquareRoot;
    }

    public void setBtnSquareRoot(JButton btnSquareRoot) {
        this.btnSquareRoot = btnSquareRoot;
    }

    public JButton getBtnSub() {
        return btnSub;
    }

    public void setBtnSub(JButton btnSub) {
        this.btnSub = btnSub;
    }

    public JButton getBtnSwap() {
        return btnSwap;
    }

    public void setBtnSwap(JButton btnSwap) {
        this.btnSwap = btnSwap;
    }

    public JLabel getButtonClear() {
        return buttonClear;
    }

    public void setButtonClear(JLabel buttonClear) {
        this.buttonClear = buttonClear;
    }

    public JLabel getLabelOperator() {
        return labelOperator;
    }

    public void setLabelOperator(JLabel labelOperator) {
        this.labelOperator = labelOperator;
    }

    public String getTxtDisplay() {
        return txtDisplay.getText();
    }

    public void setTxtDisplay(String s) {
        this.txtDisplay.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDisplay = new javax.swing.JTextField();
        btnMC = new javax.swing.JButton();
        btnMR = new javax.swing.JButton();
        btnMAdd = new javax.swing.JButton();
        btnMSub = new javax.swing.JButton();
        btnSquareRoot = new javax.swing.JButton();
        btnNum7 = new javax.swing.JButton();
        btnNum8 = new javax.swing.JButton();
        btnNum9 = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnPercent = new javax.swing.JButton();
        btnNum5 = new javax.swing.JButton();
        btnNum6 = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnNum4 = new javax.swing.JButton();
        btnFlip = new javax.swing.JButton();
        btnNum2 = new javax.swing.JButton();
        btnNum3 = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnPerform = new javax.swing.JButton();
        btnNum0 = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnSwap = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnNum1 = new javax.swing.JButton();
        labelOperator = new javax.swing.JLabel();
        buttonClear = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtDisplay.setEditable(false);
        txtDisplay.setBackground(new java.awt.Color(153, 255, 255));
        txtDisplay.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDisplay.setText("0");
        txtDisplay.setToolTipText("");

        btnMC.setBackground(new java.awt.Color(255, 255, 0));
        btnMC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMC.setText("MC");
        btnMC.setPreferredSize(new java.awt.Dimension(70, 70));

        btnMR.setBackground(new java.awt.Color(255, 255, 0));
        btnMR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMR.setText("MR");
        btnMR.setPreferredSize(new java.awt.Dimension(70, 70));

        btnMAdd.setBackground(new java.awt.Color(255, 255, 0));
        btnMAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMAdd.setText("M+");
        btnMAdd.setPreferredSize(new java.awt.Dimension(70, 70));

        btnMSub.setBackground(new java.awt.Color(255, 255, 0));
        btnMSub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMSub.setText("M-");
        btnMSub.setPreferredSize(new java.awt.Dimension(70, 70));

        btnSquareRoot.setBackground(new java.awt.Color(51, 255, 0));
        btnSquareRoot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSquareRoot.setText("√");
        btnSquareRoot.setPreferredSize(new java.awt.Dimension(70, 70));

        btnNum7.setBackground(new java.awt.Color(153, 153, 255));
        btnNum7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNum7.setText("7");
        btnNum7.setPreferredSize(new java.awt.Dimension(70, 70));

        btnNum8.setBackground(new java.awt.Color(153, 153, 255));
        btnNum8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNum8.setText("8");
        btnNum8.setPreferredSize(new java.awt.Dimension(70, 70));

        btnNum9.setBackground(new java.awt.Color(153, 153, 255));
        btnNum9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNum9.setText("9");
        btnNum9.setPreferredSize(new java.awt.Dimension(70, 70));

        btnDiv.setBackground(new java.awt.Color(51, 255, 0));
        btnDiv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDiv.setText("÷");
        btnDiv.setPreferredSize(new java.awt.Dimension(70, 70));

        btnPercent.setBackground(new java.awt.Color(51, 255, 0));
        btnPercent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPercent.setText("%");
        btnPercent.setPreferredSize(new java.awt.Dimension(70, 70));

        btnNum5.setBackground(new java.awt.Color(153, 153, 255));
        btnNum5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNum5.setText("5");
        btnNum5.setPreferredSize(new java.awt.Dimension(70, 70));

        btnNum6.setBackground(new java.awt.Color(153, 153, 255));
        btnNum6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNum6.setText("6");
        btnNum6.setPreferredSize(new java.awt.Dimension(70, 70));

        btnMulti.setBackground(new java.awt.Color(51, 255, 0));
        btnMulti.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMulti.setText("X");
        btnMulti.setPreferredSize(new java.awt.Dimension(70, 70));

        btnNum4.setBackground(new java.awt.Color(153, 153, 255));
        btnNum4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNum4.setText("4");
        btnNum4.setPreferredSize(new java.awt.Dimension(70, 70));

        btnFlip.setBackground(new java.awt.Color(51, 255, 0));
        btnFlip.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFlip.setText("1/X");
        btnFlip.setPreferredSize(new java.awt.Dimension(70, 70));

        btnNum2.setBackground(new java.awt.Color(153, 153, 255));
        btnNum2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNum2.setText("2");
        btnNum2.setPreferredSize(new java.awt.Dimension(70, 70));

        btnNum3.setBackground(new java.awt.Color(153, 153, 255));
        btnNum3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNum3.setText("3");
        btnNum3.setPreferredSize(new java.awt.Dimension(70, 70));

        btnSub.setBackground(new java.awt.Color(51, 255, 0));
        btnSub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSub.setText("-");
        btnSub.setPreferredSize(new java.awt.Dimension(70, 70));

        btnPerform.setBackground(new java.awt.Color(51, 255, 0));
        btnPerform.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPerform.setText("=");

        btnNum0.setBackground(new java.awt.Color(153, 153, 255));
        btnNum0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNum0.setText("0");
        btnNum0.setPreferredSize(new java.awt.Dimension(70, 70));

        btnDot.setBackground(new java.awt.Color(153, 153, 255));
        btnDot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDot.setText(".");
        btnDot.setPreferredSize(new java.awt.Dimension(70, 70));

        btnSwap.setBackground(new java.awt.Color(51, 255, 0));
        btnSwap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSwap.setText("+/_");
        btnSwap.setPreferredSize(new java.awt.Dimension(70, 70));

        btnAdd.setBackground(new java.awt.Color(51, 255, 0));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setText("+");
        btnAdd.setPreferredSize(new java.awt.Dimension(70, 70));

        btnNum1.setBackground(new java.awt.Color(153, 153, 255));
        btnNum1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNum1.setText("1");
        btnNum1.setPreferredSize(new java.awt.Dimension(70, 70));

        labelOperator.setText("---------------------------------------------------------------------------");

        buttonClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonClear.setText(" All Clear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDisplay)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnNum7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNum4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNum0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnNum8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNum5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNum2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNum9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNum6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNum3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSwap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(labelOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSquareRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPercent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFlip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPerform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSquareRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNum9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNum8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPercent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNum7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFlip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSwap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPerform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnFlip;
    private javax.swing.JButton btnMAdd;
    private javax.swing.JButton btnMC;
    private javax.swing.JButton btnMR;
    private javax.swing.JButton btnMSub;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnNum0;
    private javax.swing.JButton btnNum1;
    private javax.swing.JButton btnNum2;
    private javax.swing.JButton btnNum3;
    private javax.swing.JButton btnNum4;
    private javax.swing.JButton btnNum5;
    private javax.swing.JButton btnNum6;
    private javax.swing.JButton btnNum7;
    private javax.swing.JButton btnNum8;
    private javax.swing.JButton btnNum9;
    private javax.swing.JButton btnPercent;
    private javax.swing.JButton btnPerform;
    private javax.swing.JButton btnSquareRoot;
    private javax.swing.JButton btnSub;
    private javax.swing.JButton btnSwap;
    private javax.swing.JLabel buttonClear;
    private javax.swing.JLabel labelOperator;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
