package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ANH DUC
 */
public class SimpleGraph extends javax.swing.JFrame {

    /**
     * Creates new form SimpleGraph
     */
    public SimpleGraph() {
        initComponents();
    }

    public JButton getjButton_Close() {
        return jButton_Close;
    }

    public void setjButton_Close(JButton jButton_Close) {
        this.jButton_Close = jButton_Close;
    }

    public JButton getjButton_SaveImage() {
        return jButton_SaveImage;
    }

    public void setjButton_SaveImage(JButton jButton_SaveImage) {
        this.jButton_SaveImage = jButton_SaveImage;
    }

    public JButton getjButton_Visualize() {
        return jButton_Visualize;
    }

    public void setjButton_Visualize(JButton jButton_Visualize) {
        this.jButton_Visualize = jButton_Visualize;
    }

    public JMenuItem getjMenuItem_New() {
        return jMenuItem_New;
    }

    public void setjMenuItem_New(JMenuItem jMenuItem_New) {
        this.jMenuItem_New = jMenuItem_New;
    }

    public JMenuItem getjMenuItem_Open() {
        return jMenuItem_Open;
    }

    public void setjMenuItem_Open(JMenuItem jMenuItem_Open) {
        this.jMenuItem_Open = jMenuItem_Open;
    }

    public JMenuItem getjMenuItem_Save() {
        return jMenuItem_Save;
    }

    public void setjMenuItem_Save(JMenuItem jMenuItem_Save) {
        this.jMenuItem_Save = jMenuItem_Save;
    }

    public JPanel getjPanel_Output() {
        return jPanel_Output;
    }

    public void setjPanel_Output(JPanel jPanel_Output) {
        this.jPanel_Output = jPanel_Output;
    }

    public JTextArea getjTextArea_Input() {
        return jTextArea_Input;
    }

    public void setjTextArea_Input(JTextArea jTextArea_Input) {
        this.jTextArea_Input = jTextArea_Input;
    }

    public JLabel getjLabel_GraphName() {
        return jLabel_GraphName;
    }

    public void setjLabel_GraphName(JLabel jLabel_GraphName) {
        this.jLabel_GraphName = jLabel_GraphName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Input = new javax.swing.JTextArea();
        jPanel_Output = new javax.swing.JPanel();
        jButton_Visualize = new javax.swing.JButton();
        jLabel_GraphName = new javax.swing.JLabel();
        jButton_SaveImage = new javax.swing.JButton();
        jButton_Close = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_File = new javax.swing.JMenu();
        jMenuItem_New = new javax.swing.JMenuItem();
        jMenuItem_Open = new javax.swing.JMenuItem();
        jMenuItem_Save = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea_Input.setColumns(20);
        jTextArea_Input.setRows(5);
        jTextArea_Input.setText("TrafficLight{\n\t//vertices\n\tR [label=\"RED\",color=\"red\"]\n\tG [label=\"GREEN\",color=\"green\"]\n\tY [label=\"YELLOW\",color=\"yellow\"]\n\t\n\t//edges\n\tR->G [label=\"45\"]\n\tG->Y [label=\"65\"]\n\tY->R [label=\"5\"]\n}");
        jScrollPane1.setViewportView(jTextArea_Input);

        javax.swing.GroupLayout jPanel_OutputLayout = new javax.swing.GroupLayout(jPanel_Output);
        jPanel_Output.setLayout(jPanel_OutputLayout);
        jPanel_OutputLayout.setHorizontalGroup(
            jPanel_OutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );
        jPanel_OutputLayout.setVerticalGroup(
            jPanel_OutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton_Visualize.setText("Visualize");

        jLabel_GraphName.setText("Graph");

        jButton_SaveImage.setText("Save graph as Image");

        jButton_Close.setText("Close");

        jMenu_File.setText("File");

        jMenuItem_New.setText("New");
        jMenu_File.add(jMenuItem_New);

        jMenuItem_Open.setText("Open");
        jMenu_File.add(jMenuItem_Open);

        jMenuItem_Save.setText("Save");
        jMenu_File.add(jMenuItem_Save);

        jMenuBar1.add(jMenu_File);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton_Visualize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_SaveImage, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Close))
                    .addComponent(jLabel_GraphName)
                    .addComponent(jPanel_Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel_GraphName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_Output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jButton_Visualize, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_SaveImage, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jButton_Close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleGraph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Close;
    private javax.swing.JButton jButton_SaveImage;
    private javax.swing.JButton jButton_Visualize;
    private javax.swing.JLabel jLabel_GraphName;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_New;
    private javax.swing.JMenuItem jMenuItem_Open;
    private javax.swing.JMenuItem jMenuItem_Save;
    private javax.swing.JMenu jMenu_File;
    private javax.swing.JPanel jPanel_Output;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Input;
    // End of variables declaration//GEN-END:variables
}
