/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author ANH DUC
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    @Override
    public void setTitle(String string) {
        super.setTitle(string); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Notepad = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItem_New = new javax.swing.JMenuItem();
        jMenuItem_Open = new javax.swing.JMenuItem();
        jMenuItem_Save = new javax.swing.JMenuItem();
        jMenuItem_SaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Exit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItem_Undo = new javax.swing.JMenuItem();
        jMenuItem_Redo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Cut = new javax.swing.JMenuItem();
        jMenuItem_Copy = new javax.swing.JMenuItem();
        jMenuItem_Paste = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Find = new javax.swing.JMenuItem();
        jMenuItem_Replace = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_SelectAll = new javax.swing.JMenuItem();
        jMenuItem_Font = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Text Editor (MTE)");

        jTextArea_Notepad.setColumns(20);
        jTextArea_Notepad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea_Notepad.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Notepad);

        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jMenuFile.setText("File");
        jMenuFile.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jMenuItem_New.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_New.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem_New.setText("New");
        jMenuFile.add(jMenuItem_New);

        jMenuItem_Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Open.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem_Open.setText("Open");
        jMenuFile.add(jMenuItem_Open);

        jMenuItem_Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Save.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem_Save.setText("Save");
        jMenuFile.add(jMenuItem_Save);

        jMenuItem_SaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_SaveAs.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem_SaveAs.setText("Save As");
        jMenuFile.add(jMenuItem_SaveAs);
        jMenuFile.add(jSeparator1);

        jMenuItem_Exit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem_Exit.setText("Exit");
        jMenuFile.add(jMenuItem_Exit);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuEdit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jMenuItem_Undo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Undo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem_Undo.setText("Undo");
        jMenuEdit.add(jMenuItem_Undo);

        jMenuItem_Redo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Redo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem_Redo.setText("Redo");
        jMenuEdit.add(jMenuItem_Redo);
        jMenuEdit.add(jSeparator2);

        jMenuItem_Cut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Cut.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem_Cut.setText("Cut");
        jMenuEdit.add(jMenuItem_Cut);

        jMenuItem_Copy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Copy.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem_Copy.setText("Copy");
        jMenuEdit.add(jMenuItem_Copy);

        jMenuItem_Paste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Paste.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem_Paste.setText("Paste");
        jMenuEdit.add(jMenuItem_Paste);
        jMenuEdit.add(jSeparator3);

        jMenuItem_Find.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Find.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem_Find.setText("Find...");
        jMenuEdit.add(jMenuItem_Find);

        jMenuItem_Replace.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Replace.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem_Replace.setText("Replace...");
        jMenuEdit.add(jMenuItem_Replace);
        jMenuEdit.add(jSeparator4);

        jMenuItem_SelectAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_SelectAll.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem_SelectAll.setText("Select All");
        jMenuEdit.add(jMenuItem_SelectAll);

        jMenuItem_Font.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem_Font.setText("Font...");
        jMenuEdit.add(jMenuItem_Font);

        jMenuBar1.add(jMenuEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JMenuItem getjMenuItem_Copy() {
        return jMenuItem_Copy;
    }

    public void setjMenuItem_Copy(JMenuItem jMenuItem_Copy) {
        this.jMenuItem_Copy = jMenuItem_Copy;
    }

    public JMenuItem getjMenuItem_Cut() {
        return jMenuItem_Cut;
    }

    public void setjMenuItem_Cut(JMenuItem jMenuItem_Cut) {
        this.jMenuItem_Cut = jMenuItem_Cut;
    }

    public JMenuItem getjMenuItem_Exit() {
        return jMenuItem_Exit;
    }

    public void setjMenuItem_Exit(JMenuItem jMenuItem_Exit) {
        this.jMenuItem_Exit = jMenuItem_Exit;
    }

    public JMenuItem getjMenuItem_Find() {
        return jMenuItem_Find;
    }

    public void setjMenuItem_Find(JMenuItem jMenuItem_Find) {
        this.jMenuItem_Find = jMenuItem_Find;
    }

    public JMenuItem getjMenuItem_Font() {
        return jMenuItem_Font;
    }

    public void setjMenuItem_Font(JMenuItem jMenuItem_Font) {
        this.jMenuItem_Font = jMenuItem_Font;
    }

    public JMenuItem getjMenuItem_New() {
        return jMenuItem_New;
    }

    public void setjMenuItem_New(JMenuItem jMenuItem_New) {
        this.jMenuItem_New = jMenuItem_New;
    }

    public JMenuItem getjMenuItem_Open() {
        return jMenuItem_Open;
    }

    public void setjMenuItem_Open(JMenuItem jMenuItem_Open) {
        this.jMenuItem_Open = jMenuItem_Open;
    }

    public JMenuItem getjMenuItem_Paste() {
        return jMenuItem_Paste;
    }

    public void setjMenuItem_Paste(JMenuItem jMenuItem_Paste) {
        this.jMenuItem_Paste = jMenuItem_Paste;
    }

    public JMenuItem getjMenuItem_Redo() {
        return jMenuItem_Redo;
    }

    public void setjMenuItem_Redo(JMenuItem jMenuItem_Redo) {
        this.jMenuItem_Redo = jMenuItem_Redo;
    }

    public JMenuItem getjMenuItem_Replace() {
        return jMenuItem_Replace;
    }

    public void setjMenuItem_Replace(JMenuItem jMenuItem_Replace) {
        this.jMenuItem_Replace = jMenuItem_Replace;
    }

    public JMenuItem getjMenuItem_Save() {
        return jMenuItem_Save;
    }

    public void setjMenuItem_Save(JMenuItem jMenuItem_Save) {
        this.jMenuItem_Save = jMenuItem_Save;
    }

    public JMenuItem getjMenuItem_SaveAs() {
        return jMenuItem_SaveAs;
    }

    public void setjMenuItem_SaveAs(JMenuItem jMenuItem_SaveAs) {
        this.jMenuItem_SaveAs = jMenuItem_SaveAs;
    }

    public JMenuItem getjMenuItem_SelectAll() {
        return jMenuItem_SelectAll;
    }

    public void setjMenuItem_SelectAll(JMenuItem jMenuItem_SelectAll) {
        this.jMenuItem_SelectAll = jMenuItem_SelectAll;
    }

    public JMenuItem getjMenuItem_Undo() {
        return jMenuItem_Undo;
    }

    public void setjMenuItem_Undo(JMenuItem jMenuItem_Undo) {
        this.jMenuItem_Undo = jMenuItem_Undo;
    }

    public JTextArea getjTextArea_Notepad() {
        return jTextArea_Notepad;
    }

    public void setjTextArea_Notepad(JTextArea jTextArea_Notepad) {
        this.jTextArea_Notepad = jTextArea_Notepad;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainScreen().setVisible(true);
//            }
//        });
//    }

    public JMenu getjMenuEdit() {
        return jMenuEdit;
    }

    public void setjMenuEdit(JMenu jMenuEdit) {
        this.jMenuEdit = jMenuEdit;
    }

    public JMenu getjMenuFile() {
        return jMenuFile;
    }

    public void setjMenuFile(JMenu jMenuFile) {
        this.jMenuFile = jMenuFile;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem_Copy;
    private javax.swing.JMenuItem jMenuItem_Cut;
    private javax.swing.JMenuItem jMenuItem_Exit;
    private javax.swing.JMenuItem jMenuItem_Find;
    private javax.swing.JMenuItem jMenuItem_Font;
    private javax.swing.JMenuItem jMenuItem_New;
    private javax.swing.JMenuItem jMenuItem_Open;
    private javax.swing.JMenuItem jMenuItem_Paste;
    private javax.swing.JMenuItem jMenuItem_Redo;
    private javax.swing.JMenuItem jMenuItem_Replace;
    private javax.swing.JMenuItem jMenuItem_Save;
    private javax.swing.JMenuItem jMenuItem_SaveAs;
    private javax.swing.JMenuItem jMenuItem_SelectAll;
    private javax.swing.JMenuItem jMenuItem_Undo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTextArea jTextArea_Notepad;
    // End of variables declaration//GEN-END:variables
}
